#!/usr/bin/env bash
set -euo pipefail

export STORM_HOME="$(cd "$(dirname "$0")/.." && pwd)"
source "${STORM_HOME}/scripts/aux/core.bash"
source "${STORM_HOME}/scripts/aux/test.bash"

_touch() {
   touch "$1"
   truncate -s 42k "$1"
   touch -t 2201061305 "$1"
}

setup_folders() {
   local -r november="${SDCARD}/Storm/telegram/Pictures/Camera/2021-11"
   mkdir -p "$november"
   cd "$november"

   _touch 00.jpg
   _touch 01.jpg
   _touch 02\ foo\ bar.jpg

   local -r december="${SDCARD}/Storm/telegram/Pictures/Camera/2021-12"
   mkdir -p "$december"
   cd "$december"

   _touch 03.jpg

   local -r fiction="${SDCARD}/Storm/telegram/${FICTION}"
   mkdir -p "$fiction" || true
   cd "$fiction"

   _touch teletransport.txt

   touch "${november}/.DS_Store"
   touch "${fiction}/.DS_Store"
}

check_tree() {
   cd "${SDCARD}/Storm/telegram"
   tree . | test::eq "$1"
}

check_pre() {
  local -r expected="$(cat <<EOF
.
├── Books
│   └── Fiction
│       └── teletransport.txt
└── Pictures
    └── Camera
        ├── 2021-11
        │   ├── 00.jpg
        │   ├── 01.jpg
        │   └── 02\ foo\ bar.jpg
        └── 2021-12
            └── 03.jpg

6 directories, 5 files
EOF
)"

   check_tree "$expected"
}

check_pos() {
  local -r expected="$(cat <<EOF
.
├── Books
│   └── Fiction
└── Pictures
    └── Camera
        ├── 2021-11
        └── 2021-12

6 directories, 0 files
EOF
)"

   check_tree "$expected"
}

check_db() {
  local -r expected="$(cat <<EOF
=
Books
  Fiction
  Horror
Pictures
  Camera
    2021-11
    2021-12
=
2
spaceship.txt;44;201030
teletransport.txt;42;220106
3
monster.txt;22;930606
6
00.jpg;42;220106
01.jpg;42;220106
02\ foo\ bar.jpg;42;220106
7
03.jpg;42;220106
5
beach and sand.jpg;123;211229
mountain.jpg;456;211230
EOF
)"

   cat "$DB" | test::eq "$expected"
}


check_cloud_tree() {
   remove_empty_dirs "$CLOUD"
   cd "$CLOUD"

   local expected
   expected="$(cat <<EOF
.
└── Storm
    └── telegram
        ├── Books
        │   └── Fiction
        │       └── teletransport.txt
        └── Pictures
            └── Camera
                ├── 2021-11
                │   ├── 00.jpg
                │   ├── 01.jpg
                │   └── 02\ foo\ bar.jpg
                └── 2021-12
                    └── 03.jpg

8 directories, 5 files
EOF
   )"

   tree . | test::eq "$expected"
}

main() {
   cleanup
   setup_env
   setup_folders
   check_pre
   run upload-telegram-buffer
   check_pos
   check_db
   check_cloud_tree
}

main "$@"