#!/usr/bin/env bash
set -euo pipefail

export STORM_HOME="$(cd "$(dirname "$0")/.." && pwd)"
source "${STORM_HOME}/scripts/aux/core.bash"

main() {
   "${STORM_HOME}/scripts/release" aarch64-linux-android
}

main "$@"