#!/usr/bin/env bash
set -euo pipefail

export STORM_HOME="$(cd "$(dirname "$0")/.." && pwd)"
source "${STORM_HOME}/scripts/aux/core.bash"

main() {
   node "${STORM_HOME}/scripts/aux/generate-config.js" "$@"
}

main "$@"
