#!/usr/bin/env bash
set -euo pipefail

export STORM_HOME="$(cd "$(dirname "$0")/.." && pwd)"
source "${STORM_HOME}/scripts/aux/core.bash"

main() {
   set -x
   rsync \
      -e "ssh -p ${ANDROID_PORT}" \
      "${STORM_HOME}/target/aarch64-linux-android/release/${STORM_BIN_NAME}" \
      "${ANDROID_HOST}:/data/data/com.termux/files/home/${STORM_BIN_NAME}"
}

main "$@"